<template>
  <section class="legends-page"><div class="legends-container">
    <RouterLink class="back legends-back" to="/">← 返回主页</RouterLink>
    <header class="hero"><p class="eyebrow">Hearthstone Legend Archive</p><h1>炉石传说·上传说记录</h1><p>每个月用什么卡组登上传说。切换模式，回看卡组与职业的更迭。</p></header>
    <section class="summary-grid" aria-label="上传说统计">
      <article class="summary-card latest-card"><span>最近一次上传说</span><strong>{{ latest.label }}</strong><small>{{ latest.modeLabel }} · {{ latest.deck }}<template v-if="latest.hero"> · {{ latest.hero }}</template><template v-if="latest.note"> · {{ latest.note }}</template></small></article>
      <article class="summary-card"><span>上传说记录</span><strong>{{ stats.legends }}</strong><small>狂野 {{ modeCounts.wild }} · 标准 {{ modeCounts.standard }} · 幻变 {{ modeCounts.twist }}</small></article>
      <article class="summary-card"><span>最常用职业</span><strong>{{ stats.favoriteHero || '—' }}</strong><small>{{ stats.favoriteHeroCount }} 次上传说</small></article>
    </section>
    <nav class="mode-tabs" aria-label="模式筛选"><button v-for="mode in tabModes" :key="mode.key" type="button" :class="{ active: selectedMode === mode.key }" @click="selectedMode = mode.key">{{ mode.icon }} {{ mode.label }} <small>{{ mode.key === 'all' ? stats.legends : modeCounts[mode.key] }}</small></button></nav>
    <section class="records-panel"><div class="panel-heading"><div><h2>{{ currentMode.label }}上传说历程</h2><p>只展示上传说的模式；未来空白月份保留为待记录。</p></div><div class="legend"><span class="legend-hit">✦ 已上传说</span></div></div>
      <div class="year-list"><article v-for="year in visibleYears" :key="year" class="year-section"><h3>{{ year }} 年 <small>{{ yearSummary(year) }}</small></h3><div class="month-grid">
        <article v-for="record in recordsForYear(year)" :key="record.month" class="month-card" :class="cardState(record)"><header><span>{{ record.month }} 月</span><em v-if="isRecordLatest(record)">最近</em></header>
          <template v-if="selectedMode === 'all'"><div v-for="mode in visibleModes(record)" :key="mode.key" class="mode-row"><div class="mode-meta"><span class="mode-name" :style="{ '--mode-color': mode.color }">{{ mode.label }}</span><small v-if="record[mode.key].hero">· {{ record[mode.key].hero }}</small></div><b>{{ record[mode.key].deck }}<em v-if="record[mode.key].note" class="hit-note">{{ record[mode.key].note }}</em></b></div></template>
          <template v-else><div v-if="record[selectedMode]" class="single-hit"><b>{{ record[selectedMode].deck }}<em v-if="record[selectedMode].note" class="hit-note">{{ record[selectedMode].note }}</em></b><span v-if="record[selectedMode].hero">{{ record[selectedMode].hero }}</span><i :style="{ background: currentMode.color }"></i></div><div v-else class="single-empty">暂无记录</div></template>
        </article>
      </div></article></div>
    </section>
    <section class="records-panel class-panel"><div class="panel-heading"><div><h2>职业上传说次数</h2><p>所有已上传说记录汇总；卡条越长，出现次数越多。</p></div></div><div class="hero-bars"><div v-for="item in stats.heroCounts" :key="item.name" class="hero-bar"><span>{{ item.name }}</span><div><i :style="{ width: `${item.percent}%` }"></i></div><b>{{ item.count }}</b></div></div></section>
  </div></section>
</template>
<script setup>
import { computed, ref } from 'vue'
import { legendRecords, modes } from '../data/legendRecords.js'
const selectedMode = ref('all')
const tabModes = [{ key: 'all', label: '全部模式', icon: '✦' }, ...modes]
const currentMode = computed(() => tabModes.find((mode) => mode.key === selectedMode.value))
const years = [...new Set(legendRecords.map((record) => record.year))].sort((a, b) => b - a)
const recordsForYear = (year) => legendRecords.filter((record) => record.year === year && (selectedMode.value === 'all' || record[selectedMode.value]?.deck))
const visibleYears = computed(() => years.filter((year) => recordsForYear(year).length))
const allEntries = computed(() => legendRecords.flatMap((record) => modes.map((mode) => ({ ...record[mode.key], mode, record })).filter((entry) => entry.deck)))
const modeCounts = computed(() => Object.fromEntries(modes.map((mode) => [mode.key, allEntries.value.filter((entry) => entry.mode.key === mode.key).length])))
const latest = computed(() => { const entry = [...allEntries.value].at(-1); return { label: `${entry.record.year}年${entry.record.month}月`, modeLabel: entry.mode.label, deck: entry.deck, hero: entry.hero, note: entry.note } })
const stats = computed(() => { const heroCounts = Object.entries(allEntries.value.reduce((counts, entry) => { if (entry.hero) counts[entry.hero] = (counts[entry.hero] || 0) + 1; return counts }, {})).map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count); const max = heroCounts[0]?.count || 1; heroCounts.forEach((item) => { item.percent = item.count / max * 100 }); return { legends: allEntries.value.length, recorded: legendRecords.flatMap((record) => modes.map((mode) => record[mode.key])).filter(Boolean).length, missed: legendRecords.flatMap((record) => modes.map((mode) => record[mode.key])).filter((entry) => entry?.status === 'missed').length, favoriteHero: heroCounts[0]?.name, favoriteHeroCount: heroCounts[0]?.count || 0, heroCounts } })
const visibleModes = (record) => modes.filter((mode) => record[mode.key]?.deck)
const cardState = (record) => modes.some((mode) => record[mode.key]?.deck) ? 'has-record' : ''
const latestKey = `${latest.value.label}-${latest.value.modeLabel}`
const isRecordLatest = (record) => modes.some((mode) => `${record.year}年${record.month}月-${mode.label}` === latestKey)
const yearSummary = (year) => { const entries = recordsForYear(year).flatMap((record) => modes.map((mode) => record[mode.key])).filter((entry) => entry?.deck); return entries.length ? `已上传说 ${entries.length} 次` : '待记录' }
</script>
<style scoped>
.legends-page { min-height: calc(100vh - var(--header-h)); padding: 48px 20px 70px; background: radial-gradient(circle at 10% 4%, #35265a 0, transparent 24rem), radial-gradient(circle at 88% 24%, #2d5b67 0, transparent 27rem), #131520; color: #f5f1e8; }.legends-container { max-width: 1160px; margin: auto; }.legends-back { color: #b9b5ca; }.legends-back:hover { color: #fff; }.eyebrow { color: #eebd65; }.hero h1 { font-size: clamp(2.1rem, 5vw, 3.45rem); margin: 4px 0 10px; letter-spacing: -.04em; }.hero > p:last-child { margin: 0; color: #c3becc; }
.summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 30px 0 20px; }.summary-card, .records-panel { border: 1px solid rgba(234, 213, 174, .16); border-radius: 14px; background: rgba(26, 28, 43, .82); box-shadow: 0 18px 38px rgba(0, 0, 0, .2); }.summary-card { display: flex; min-height: 118px; padding: 17px; flex-direction: column; }.summary-card span, .summary-card small { color: #aaa5b8; font-size: .86rem; }.summary-card strong { margin: 4px 0; color: #f3d28a; font-size: 1.7rem; line-height: 1.2; }.latest-card { background: linear-gradient(135deg, rgba(102, 72, 184, .5), rgba(30, 37, 59, .92)); }
.mode-tabs { display: flex; flex-wrap: wrap; gap: 8px; margin: 0 0 20px; }.mode-tabs button { border: 1px solid rgba(255,255,255,.15); border-radius: 999px; padding: 8px 14px; background: rgba(255,255,255,.05); color: #c8c3d0; font: inherit; font-weight: 700; cursor: pointer; }.mode-tabs button.active { border-color: #efc96f; background: #edc96f; color: #29202f; }.mode-tabs small { opacity: .72; margin-left: 3px; }.records-panel { padding: 22px; }.panel-heading { display: flex; justify-content: space-between; gap: 18px; align-items: flex-start; margin-bottom: 20px; }.panel-heading h2 { margin: 0 0 4px; font-size: 1.2rem; }.panel-heading p { margin: 0; color: #aaa5b8; font-size: .9rem; }.legend { display: flex; flex-wrap: wrap; gap: 12px; color: #aaa5b8; font-size: .78rem; white-space: nowrap; }.legend-hit { color: #f3d28a; }.legend-missed { color: #df8893; }
.year-section + .year-section { margin-top: 27px; }.year-section h3 { display: flex; align-items: baseline; gap: 8px; margin: 0 0 10px; font-size: 1.12rem; }.year-section h3 small { color: #928da0; font-size: .78rem; font-weight: 500; }.month-grid { display: grid; grid-template-columns: repeat(6, minmax(0, 1fr)); gap: 10px; }.month-card { min-height: 126px; border: 1px solid rgba(255,255,255,.09); border-radius: 10px; padding: 10px; background: rgba(255,255,255,.025); }.month-card.has-record, .month-card.is-hit { border-color: rgba(234, 201, 111, .3); background: linear-gradient(145deg, rgba(97, 69, 158, .22), rgba(255,255,255,.03)); }.month-card.is-missed { border-color: rgba(211, 109, 126, .28); }.month-card header { display: flex; justify-content: space-between; color: #aaa5b8; font-size: .8rem; font-weight: 700; }.month-card header em { padding: 1px 5px; border-radius: 99px; background: #edc96f; color: #332637; font-size: .67rem; font-style: normal; }.mode-row { display: grid; grid-template-columns: 34px 1fr; align-items: center; column-gap: 5px; min-height: 25px; margin-top: 5px; font-size: .76rem; }.mode-name { color: var(--mode-color); font-size: .67rem; font-weight: 800; }.mode-row b { overflow: hidden; color: #ebe7ed; text-overflow: ellipsis; white-space: nowrap; }.mode-row small { color: #bca2dd; }.mode-row.is-missed b { color: #dc8d98; }.empty { color: #666474; }.single-hit { position: relative; display: grid; gap: 5px; margin-top: 18px; }.single-hit b { font-size: 1.08rem; }.single-hit span { color: #c8b4e4; font-size: .82rem; }.single-hit i { position: absolute; top: 0; right: 0; width: 8px; height: 8px; border-radius: 50%; box-shadow: 0 0 12px currentColor; }.single-missed, .single-empty { margin-top: 24px; color: #dc8d98; font-weight: 700; }.single-empty { color: #666474; font-weight: 500; }
.class-panel { margin-top: 18px; }.hero-bars { display: grid; gap: 10px; max-width: 700px; }.hero-bar { display: grid; grid-template-columns: 64px 1fr 24px; align-items: center; gap: 10px; }.hero-bar > span { color: #d4cedc; font-size: .84rem; font-weight: 700; }.hero-bar > div { height: 9px; overflow: hidden; border-radius: 999px; background: rgba(255,255,255,.1); }.hero-bar i { display: block; height: 100%; border-radius: inherit; background: linear-gradient(90deg, #7f60d3, #edc96f); }.hero-bar b { color: #f3d28a; font-size: .82rem; text-align: right; }
.month-card.has-record, .month-card.is-hit { border-color: rgba(234, 201, 111, .3); }.month-card.is-missed { border-color: rgba(255,255,255,.09); }.month-card header { color: #c2bdca; font-size: .9rem; }.mode-row { grid-template-columns: 1fr; gap: 2px; margin-top: 8px; }.mode-meta { display: flex; align-items: baseline; gap: 3px; line-height: 1.1; }.mode-name { font-size: .82rem; }.mode-meta small { color: #bca2dd; font-size: .78rem; white-space: nowrap; }.mode-row b { font-size: .98rem; line-height: 1.25; }.mode-row > small { display: none; }.mode-row.is-missed, .single-missed { display: none; }
.hit-note { display: inline-block; margin-left: 5px; padding: 1px 6px; border-radius: 99px; background: rgba(237, 201, 111, .16); color: #f3d28a; font-size: .62rem; font-style: normal; font-weight: 700; vertical-align: 2px; white-space: nowrap; }
@media (max-width: 900px) { .summary-grid { grid-template-columns: repeat(3, 1fr); }.month-grid { grid-template-columns: repeat(4, minmax(0, 1fr)); } } @media (max-width: 580px) { .legends-page { padding: 28px 14px 50px; }.summary-grid { grid-template-columns: 1fr; gap: 8px; }.summary-card { min-height: 104px; padding: 13px; }.summary-card strong { font-size: 1.45rem; }.records-panel { padding: 15px; }.panel-heading { display: grid; }.month-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }.month-card { min-height: 126px; }.mode-tabs button { padding: 7px 10px; font-size: .82rem; } }
</style>
